.TH "api.serializers.UserTicketsSerializer.Meta" 3 "Fri Jan 13 2017" "Version v1.0" "Tickets backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api.serializers.UserTicketsSerializer.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP = \fBUserTickets\fP"
.br
.ti -1c
.RI "tuple \fBfields\fP"
.br
.ti -1c
.RI "tuple \fBread_only_fields\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "tuple api\&.serializers\&.UserTicketsSerializer\&.Meta\&.fields\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  ('url', 'user_id',
                  'ticket_id', 'status',
                  'valid_to_date')
.fi
.SS "tuple api\&.serializers\&.UserTicketsSerializer\&.Meta\&.read_only_fields\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  ('url', 'user_id',
                            'valid_to_date')
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Tickets backend from the source code\&.
