.TH "api.serializers.UserTicketsSerializer" 3 "Fri Jan 13 2017" "Version v1.0" "Tickets backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api.serializers.UserTicketsSerializer
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModelSerializer\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBcreate\fP (self, validated_data)"
.br
.ti -1c
.RI "def \fBupdate\fP (self, instance, validated_data)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tickets backend from the source code\&.
