.TH "api.serializers.TicketSerializer.Meta" 3 "Fri Jan 13 2017" "Version v1.0" "Tickets backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api.serializers.TicketSerializer.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP = \fBTicket\fP"
.br
.ti -1c
.RI "tuple \fBfields\fP"
.br
.ti -1c
.RI "tuple \fBread_only_fields\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "tuple api\&.serializers\&.TicketSerializer\&.Meta\&.fields\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  ('url', 'name',
                  'price', 'description',
                  'time_of_validity', 'time_unit')
.fi
.SS "tuple api\&.serializers\&.TicketSerializer\&.Meta\&.read_only_fields\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  ('url', 'name',
                  'price', 'description',
                  'time_of_validity', 'time_unit')
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Tickets backend from the source code\&.
