.TH "api.serializers.UserSerializer.Meta" 3 "Fri Jan 13 2017" "Version v1.0" "Tickets backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api.serializers.UserSerializer.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP = User"
.br
.ti -1c
.RI "tuple \fBfields\fP"
.br
.ti -1c
.RI "tuple \fBwrite_only_fields\fP = ('password',)"
.br
.ti -1c
.RI "tuple \fBread_only_fields\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "tuple api\&.serializers\&.UserSerializer\&.Meta\&.fields\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  ('url', 'username',
                  'password', 'first_name',
                  'last_name', 'email')
.fi
.SS "tuple api\&.serializers\&.UserSerializer\&.Meta\&.read_only_fields\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=  ('is_staff',
                            'is_superuser', 'is_active',
                            'date_joined',)
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Tickets backend from the source code\&.
