.TH "api.serializers.TicketSerializer" 3 "Fri Jan 13 2017" "Version v1.0" "Tickets backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api.serializers.TicketSerializer
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModelSerializer\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMeta\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tickets backend from the source code\&.
