.TH "api.views.AccountViewSet" 3 "Fri Jan 13 2017" "Version v1.0" "Tickets backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api.views.AccountViewSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModelViewSet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget_permissions\fP (self)"
.br
.ti -1c
.RI "def \fBget_queryset\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBqueryset\fP = Account\&.objects\&.all()"
.br
.ti -1c
.RI "\fBserializer_class\fP = \fBAccountSerializer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    View for serialized Account model

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def api\&.views\&.AccountViewSet\&.get_permissions ( self)"

.PP
.nf
    Allow access only for authenticated users.

.fi
.PP
 
.SS "def api\&.views\&.AccountViewSet\&.get_queryset ( self)"

.PP
.nf
    Filtering records to show only records which user is owner.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tickets backend from the source code\&.
