.TH "api.apps.ApiConfig" 3 "Fri Jan 13 2017" "Version v1.0" "Tickets backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api.apps.ApiConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppConfig\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP = 'api'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tickets backend from the source code\&.
